---
instance_name: 'vanilla'
subdomain: ''
hostname: '{{ansible_hostname}}'
url_path: 'r/' # following slash
mediawiki_dir: '{% if url_path %}{{url_path}}{% endif %}{{instance_name}}'
mediawiki_path: '/var/www/html/{{mediawiki_dir}}'
mediawiki_language: 'en'
mediawiki_version: REL1_34
server_name: '{% if subdomain %}{{subdomain}}.{% endif %}{{hostname}}'
base_uri: 'http://{{server_name}}/{{mediawiki_dir}}'

mediawiki_skins:
- Vector

admin_user:
  name: Admin
  pass: '{{ confident_wiki_admin_pwd }}'
mediawiki_db:
  connection: mysql
  name: mw_{{instance_name}}
  user: mw_{{ instance_name | truncate(16-3, True, '') }}
  password: '{{ confident_wiki_db_pwd }}'

smw_version: '~3.1'
semanticscribunto_version: '~2.1'
semanticite_version: '~2.1'
semanticformats_version: '~3.1'