---
instance_name: '{{ansible_hostname}}'
subdomain: ''
hostname: '{{ansible_hostname}}'
mediawiki_dir: '{{instance_name}}'
mediawiki_path: '/var/www/html/{{instance_name}}'
mediawiki_language: 'en'
mediawiki_version: REL1_34
server_name: '{% if subdomain %}{{subdomain}}.{% endif %}{{hostname}}'
base_uri: 'http://{{server_name}}/{{mediawiki_dir}}'

mediawiki_skins:
- Vector

admin_user:
  name: Admin
  pass: adminpwd
mediawiki_db:
  connection: mysql
  name: mw_{{instance_name}}
  user: mw_{{ instance_name | truncate(16-3, True, '') }}
  password: mediawiki

smw_version: '~3.1'
semanticscribunto_version: '~2.1'
semanticite_version: '~2.1'
semanticformats_version: '~3.1'