---
- name: Install Composer Extensions debug
  debug:
    msg: composer require {{ item.composer_cmd }} --update-no-dev
  with_items:
    - '{{ extensions_composer }}'
  
- name: 1. Install Composer Extensions
  shell:
    cmd: composer require {{ item.composer_cmd }} --update-no-dev
    chdir: '{{ mediawiki_path }}'
  with_items:
    - '{{ extensions_composer }}'
      
- name: 2. Enable Composer Extensions
  lineinfile:
    path: '{{ mediawiki_path }}/LocalSettings.php'
    insertafter: 'EOF'
    line: "# {{ item.ext_name }}\n{{item.load_strs | join('\n')}}\n"
    state: present
  with_items:
    - '{{ extensions_composer }}'

- name: 3. Run the maintenance script
  shell: 
    cmd: php maintenance/update.php
    chdir: '{{ mediawiki_path }}'
