---

- name: runJobs every minute
  cron: 
    name: "run MW jobs"
    minute: "*/1"
    job: ' /usr/bin/php {{ mediawiki_path }}/maintenance/runJobs.php --maxtime=3600'
  tags: localsettings


- name: Settings in LocalSetting.php
  blockinfile:
    path: '{{mediawiki_path}}/LocalSettings.php'
    insertafter: EOF
    block: |
        # Job are run by cron
        $wgJobRunRate = 0;
        # Permissions
        $wgGroupPermissions['*']['read'] = true;
        $wgGroupPermissions['*']['edit'] = false;
        $wgGroupPermissions['user']['edit'] = true;
        $wgGroupPermissions['*']['createaccount'] = false;
        # uploads
        $wgEnableUploads = true;
        $wgUseImageMagick = true;
        $wgImageMagickConvertCommand = "/usr/bin/convert";
        # Debug
        $wgShowExceptionDetails=true;
        $wgShowSQLError=true;
        $wgShowDBErrorBacktrace=true;
        error_reporting(-1);
        ini_set('display_errors',1);
  tags: localsettings

- name: write permissions to images/
  file:
    path: '{{mediawiki_path}}/images'
    state: directory
    mode: a+rw
    recurse: yes
  tags: localsettings
