---
- name: 0. Is MW dir present?
  stat:
    path: '{{ mediawiki_path }}'
  register: stat_mediawiki_repo

- name: 1. Clone mediawiki
  git:
    repo: 'https://gerrit.wikimedia.org/r/p/mediawiki/core.git'
    dest: '{{ mediawiki_path }}'
    version: "{{mediawiki_version|default('HEAD')}}"
    depth: 1
    force: yes
  when: stat_mediawiki_repo.stat.exists == false

- include: composer.yml


- name: 3. Install mediawiki dependencies
  shell: 
    cmd: composer install --no-dev
    chdir: '{{ mediawiki_path }}'
  become: no

- include: mysql.yml
  when: mediawiki_db.connection == "mysql"

# - name: 4. Install mediawiki skins
#   git:
#     repo: "https://gerrit.wikimedia.org/r/mediawiki/skins/{{item}}"
#     dest: "{{ mediawiki_path }}/skins/{{item}}"
#     version: "{{mediawiki_version|default('HEAD')}}"
#   with_items: '{{mediawiki_skins}}'

- name: Is LocalSettings.php present?
  stat:
    path: '{{ mediawiki_path }}/LocalSettings.php'
  register: stat_LocalSettings

- name: 4. Discard old LocalSettings
  file:
    path: '{{ mediawiki_path }}/LocalSettings.php'
    state: absent
  when: stat_LocalSettings.stat.exists == True


- name: 5. Install mediawiki
  command: php {{ mediawiki_path }}/maintenance/install.php
    --dbname {{mediawiki_db.name}}
    --dbuser {{mediawiki_db.user}}
    --dbpass {{mediawiki_db.password}}
    --dbtype {{mediawiki_db.connection}}
    --lang {{mediawiki_language}}
    --pass {{admin_user.pass}}
    --scriptpath /'{{mediawiki_dir}}'
    --server 'http://{{inventory_hostname}}'
    {{instance_name}} {{admin_user.name}}
  args:
    creates: '{{ mediawiki_path }}/LocalSettings.php'

- include: extensions.yml

- include: extensions_composer.yml


- name: Mediawiki URL
  debug:
    msg: "WIKI: http://{{inventory_hostname}}/{{mediawiki_dir}}"

# - name: 6. Enable clean URL's
#   lineinfile:
#     dest: '{{ mediawiki_path }}/LocalSettings.php'
#     line: '$wgArticlePath = "/$1";'
#     regexp: '\$wgArticlePath'
