---
instance_name: 'vanilla'
mediawiki_language: 'en'
mediawiki_version: REL1_34

debug:
  msg: "script_path: {{ mw_script_path }} mediawiki_path: {{ mediawiki_path }}"

mediawiki_skins:
- Vector

admin_user:
  name: Admin
  pass: '{{ confident_wiki_admin_pwd }}'
mediawiki_db:
  connection: mysql
  name: mw_{{instance_name}}
  user: mw_{{ instance_name | truncate(16-3, True, '') }}
  password: '{{ confident_wiki_db_pwd }}'

smw_version: '~3.1'
semanticscribunto_version: '~2.1'
semanticite_version: '~2.1'
semanticformats_version: '~3.1'
maps_version: '~7.0'